+ this notebook generates Backend-required files to view a project with the DataDiVR (preview or VR)
+ STEP 1 and the "create a graph" section contains a template graph writing a required format (json) to then use the generate-project functions of the DataDiVR backend

+ STEP 2 to actually generate BACKEND project files.

In [1]:
import networkx as nx
import json 
import os

# these are the two functions one needs to create a JSON file to upload and create the project in the backend 
import nx2json as nx2j
import uploaderGraph as uG


## How this is meant to be used:
+ Create an nx.Graph Object 

+ set attributes in the nx.Graph (optional, all can be empty) e.g. node positions ("pos") and colors ("nodecolor") and link colors ("linkcolor")

+ use the "create_project" function (down below to generate your project for the platform)

# make VR project

In [3]:
# make nx.graph from tsv file 
import pandas as pd
df_nodes = pd.read_csv("temp-files/students/positions_per_location.tsv", sep="\t")  

# add color columns r g b a (ideally this is in the file already) 
df_nodes['r'] = 100
df_nodes['g'] = 150
df_nodes['b'] = 200
df_nodes['a'] = 200

# get links from DATA (chloe) source 
df_links_uniprot = pd.read_csv("temp-files/students/consensus_ppi_bioplex_biogrid_intact_huri_edgelist.tsv", sep="\t", header=None)

df_nodes

     Node ID            x            y            z    r    g    b    a
0     Q6UWY0  -222.357100  1687.018840  3782.702621  100  150  200  200
1     Q9H0U3  3961.390715  2148.441916 -2145.565466  100  150  200  200
2     Q05707 -2002.859816  2023.204403  4129.907382  100  150  200  200
3     P20036   145.879351  1079.085284  4900.218594  100  150  200  200
4     Q13586  3634.210858 -1635.926845  -385.922313  100  150  200  200
...      ...          ...          ...          ...  ...  ...  ...  ...
3467  Q8N9T8   828.351138  1259.441155   566.447491  100  150  200  200
3468  P42677  1307.502933  1059.026024   548.535570  100  150  200  200
3469  Q9BQ39   452.970782  1189.869517   291.792645  100  150  200  200
3470  Q8N5L8   539.443722   397.857802   -68.834785  100  150  200  200
3471  O15169  1373.870579   915.618803  -153.669733  100  150  200  200

[3472 rows x 8 columns]

In [5]:
G = nx.Graph()
G.add_nodes_from(df_nodes['Node ID'])
for i, row in df_nodes.iterrows():
    G.nodes[row['Node ID']]['pos'] = [row['x'], row['y'], row['z']]
    G.nodes[row['Node ID']]['nodecolor'] = [row['r'], row['g'], row['b'], row['a']]
G.add_edges_from(df_links_uniprot.values)

# add positions to Graph pos attributes 
# go through all graph nodes - and if none 
nx.set_node_attributes(G, {row['Node ID']: [row['x'], row['y'], row['z']] for i, row in df_nodes.iterrows()}, 'pos')

print(f"Graph has {G.number_of_nodes()} nodes and {G.number_of_edges()} edges.")

Graph has 19555 nodes and 313667 edges.

In [62]:
df_n_comp = pd.read_csv("temp-files/students/protein_location_HPA_GO.tsv", sep="\t")
df_n_comp

         protein               location source(s)
0         DIAPH2                Cytosol        GO
1          ACTL8                Cytosol       HPA
2           FZD2         Primary cilium       HPA
3           PKN2        Plasma membrane    HPA;GO
4          CREB3  Endoplasmic reticulum        GO
...          ...                    ...       ...
28013  IGKV2D-28        Plasma membrane        GO
28014      CLDN1        Plasma membrane        GO
28015      ANXA6         Primary cilium       HPA
28016       SHC4                Cytosol       HPA
28017     EPS8L2                Cytosol       HPA

[28018 rows x 3 columns]

In [63]:
# from UNITPROT to gene symbol 

# modify ids from uniprot to gene symbol 
df_uniprot_genesym = pd.read_csv("temp-files/students/d_uniprot_to_symbol_20251120.tsv", sep="\t")
df_uniprot_genesym_dict = pd.Series(df_uniprot_genesym.symbol.values,index=df_uniprot_genesym.uniprotid).to_dict()

# replace node ids in graph
mapping_dict = {}
for n in G.nodes():
    if n in df_uniprot_genesym_dict:
        mapping_dict[n] = df_uniprot_genesym_dict[n]
G = nx.relabel_nodes(G, mapping_dict)

print(f"After relabeling, graph has {G.number_of_nodes()} nodes and {G.number_of_edges()} edges.")

After relabeling, graph has 18346 nodes and 308377 edges.

In [64]:
# node attributes
node_attributes = {}

for n in G.nodes(): 
    comp = df_n_comp[df_n_comp['protein'] == n]['location'].values
    if len(comp) > 0:
        node_attributes[n] = {'location': comp[0]}
    else:
        node_attributes[n] = {'location': 'unknown'}

In [65]:
node_attributes

{'STIM1': {'location': 'Plasma membrane'},
 'AGPAT4': {'location': 'Endoplasmic reticulum'},
 'P32969': {'location': 'unknown'},
 'RPL27A': {'location': 'Nucleoplasm'},
 'NCK1': {'location': 'Plasma membrane'},
 'APOA2': {'location': 'Cytosol'},
 'BSG': {'location': 'Golgi apparatus'},
 'EMC10': {'location': 'Endoplasmic reticulum'},
 'PTPN1': {'location': 'Plasma membrane'},
 'TMED9': {'location': 'Endoplasmic reticulum'},
 'GPR37': {'location': 'Plasma membrane'},
 'DNAJA1': {'location': 'Cytosol'},
 'ORMDL1': {'location': 'Endoplasmic reticulum'},
 'TMPRSS3': {'location': 'Endoplasmic reticulum'},
 'PTPN5': {'location': 'Nucleoplasm'},
 'TPTE': {'location': 'Cytosol'},
 'BET1': {'location': 'Golgi apparatus'},
 'DDOST': {'location': 'Plasma membrane'},
 'RNF19B': {'location': 'Endoplasmic reticulum'},
 'ATXN3': {'location': 'Nucleoplasm'},
 'ERLIN1': {'location': 'Endoplasmic reticulum'},
 'RNF185': {'location': 'Endoplasmic reticulum'},
 'COL5A1': {'location': 'Endoplasmic reticulum'},
 'FGFR3': {'location': 'Plasma membrane'},
 'SOAT1': {'location': 'Endoplasmic reticulum'},
 'CDK1': {'location': 'Mitochondria'},
 'IER3IP1': {'location': 'Endoplasmic reticulum'},
 'RPS2': {'location': 'Nucleoplasm'},
 'HMOX1': {'location': 'Endoplasmic reticulum'},
 'FAM20C': {'location': 'Golgi apparatus'},
 'ESYT2': {'location': 'Plasma membrane'},
 'PDZD8': {'location': 'Nucleoli'},
 'CDC42': {'location': 'Centrosome'},
 'COMT': {'location': 'Plasma membrane'},
 'RPL10L': {'location': 'Endoplasmic reticulum'},
 'UFL1': {'location': 'Nucleoplasm'},
 'CFTR': {'location': 'Plasma membrane'},
 'YWHAE': {'location': 'Mitochondria'},
 'PTDSS1': {'location': 'Endoplasmic reticulum'},
 'MAP3K5': {'location': 'Cytosol'},
 'PRKCA': {'location': 'Nucleoplasm'},
 'RNF5': {'location': 'Endoplasmic reticulum'},
 'PLN': {'location': 'Endoplasmic reticulum'},
 'CGRRF1': {'location': 'Endoplasmic reticulum'},
 'CALR': {'location': 'Actin filaments'},
 'TMBIM6': {'location': 'Endoplasmic reticulum'},
 'RPS6': {'location': 'Endoplasmic reticulum'},
 'ACE2': {'location': 'Plasma membrane'},
 'NOTCH1': {'location': 'Cytosol'},
 'RPS29': {'location': 'Endoplasmic reticulum'},
 'CLU': {'location': 'Cytosol'},
 'EEF1G': {'location': 'Cytosol'},
 'TAP1': {'location': 'Endoplasmic reticulum'},
 'SSR1': {'location': 'Endoplasmic reticulum'},
 'RPS27A': {'location': 'Mitochondria'},
 'LMAN1': {'location': 'Endoplasmic reticulum'},
 'UGT8': {'location': 'Endoplasmic reticulum'},
 'SCAP': {'location': 'Endoplasmic reticulum'},
 'CKAP4': {'location': 'Plasma membrane'},
 'ARL6IP5': {'location': 'Endoplasmic reticulum'},
 'MAPK3': {'location': 'Endoplasmic reticulum'},
 'PSEN2': {'location': 'Endoplasmic reticulum'},
 'WLS': {'location': 'Plasma membrane'},
 'UFD1': {'location': 'Nucleoplasm'},
 'ADAMTSL4': {'location': 'Plasma membrane'},
 'LNPK': {'location': 'Endoplasmic reticulum'},
 'AMFR': {'location': 'Golgi apparatus'},
 'STUB1': {'location': 'Nucleoplasm'},
 'EBP': {'location': 'Endoplasmic reticulum'},
 'SAR1A': {'location': 'Endoplasmic reticulum'},
 'PRKN': {'location': 'Nucleoplasm'},
 'FAM234B': {'location': 'Endoplasmic reticulum'},
 'SEL1L': {'location': 'Endoplasmic reticulum'},
 'UBIAD1': {'location': 'Endoplasmic reticulum'},
 'SACM1L': {'location': 'Endoplasmic reticulum'},
 'RPS21': {'location': 'Nucleoplasm'},
 'PDIA6': {'location': 'Endoplasmic reticulum'},
 'ARSK': {'location': 'Nucleoplasm'},
 'ERLEC1': {'location': 'Endoplasmic reticulum'},
 'TMEM97': {'location': 'Plasma membrane'},
 'RPN1': {'location': 'Cytosol'},
 'RTN3': {'location': 'Golgi apparatus'},
 'HLA-B': {'location': 'Endoplasmic reticulum'},
 'COPB2': {'location': 'Cytosol'},
 'AUP1': {'location': 'Nucleoplasm'},
 'KRAS': {'location': 'Cytosol'},
 'FN1': {'location': 'Plasma membrane'},
 'RPS8': {'location': 'Plasma membrane'},
 'CNPY3': {'location': 'Plasma membrane'},
 'RPL26': {'location': 'Cytosol'},
 'FDFT1': {'location': 'Endoplasmic reticulum'},
 'RPL28': {'location': 'Cytosol'},
 'ELOVL4': {'location': 'Endoplasmic reticulum'},
 'RPS3': {'location': 'Cytosol'},
 'TMEM86B': {'location': 'Endoplasmic reticulum'},
 'PLOD1': {'location': 'Endoplasmic reticulum'},
 'CDK5RAP3': {'location': 'Microtubules'},
 'JPH3': {'location': 'Nucleoplasm'},
 'UBA1': {'location': 'Nucleoplasm'},
 'EIF2AK3': {'location': 'Cytosol'},
 'COL4A5': {'location': 'Plasma membrane'},
 'SEC22B': {'location': 'Endoplasmic reticulum'},
 'ATP2A2': {'location': 'Plasma membrane'},
 'ARL6IP1': {'location': 'Endoplasmic reticulum'},
 'REEP6': {'location': 'Endoplasmic reticulum'},
 'MIA3': {'location': 'Endoplasmic reticulum'},
 'RPS20': {'location': 'Nucleoplasm'},
 'BNIP1': {'location': 'Mitochondria'},
 'NPLOC4': {'location': 'Cytosol'},
 'GIMAP1': {'location': 'Endoplasmic reticulum'},
 'COPG2': {'location': 'Cytosol'},
 'SEC62': {'location': 'Intermediate filaments'},
 'CCDC47': {'location': 'Cytosol'},
 'DERL2': {'location': 'Endoplasmic reticulum'},
 'RPL5': {'location': 'Nucleoplasm'},
 'RTN4': {'location': 'Endoplasmic reticulum'},
 'RPL37A': {'location': 'Cytosol'},
 'SRPRB': {'location': 'Endoplasmic reticulum'},
 'STX5': {'location': 'Golgi apparatus'},
 'RPL7': {'location': 'Cytosol'},
 'ATP2A1': {'location': 'Endoplasmic reticulum'},
 'HADHB': {'location': 'Endoplasmic reticulum'},
 'APP': {'location': 'Cytosol'},
 'STING1': {'location': 'Cytosol'},
 'TMED7': {'location': 'Endoplasmic reticulum'},
 'EDEM1': {'location': 'Endoplasmic reticulum'},
 'SEC63': {'location': 'Endoplasmic reticulum'},
 'VRK2': {'location': 'Endoplasmic reticulum'},
 'TGOLN2': {'location': 'Golgi apparatus'},
 'ANXA7': {'location': 'Endoplasmic reticulum'},
 'COL1A1': {'location': 'Endoplasmic reticulum'},
 'GOLM1': {'location': 'Endoplasmic reticulum'},
 'MMGT1': {'location': 'Endoplasmic reticulum'},
 'CD74': {'location': 'Golgi apparatus'},
 'RHBDD1': {'location': 'Endoplasmic reticulum'},
 'RPL18': {'location': 'Cytosol'},
 'RPL4': {'location': 'Cytosol'},
 'DERL1': {'location': 'Endoplasmic reticulum'},
 'MAPK1': {'location': 'Endoplasmic reticulum'},
 'CREB3L1': {'location': 'Endoplasmic reticulum'},
 'RPL29': {'location': 'Cytosol'},
 'SPCS1': {'location': 'Golgi apparatus'},
 'SERPINH1': {'location': 'Endoplasmic reticulum'},
 'ADAM10': {'location': 'Actin filaments'},
 'ZDHHC12': {'location': 'Golgi apparatus'},
 'PRAF2': {'location': 'Endoplasmic reticulum'},
 'SET': {'location': 'Nucleoplasm'},
 'HLA-A': {'location': 'Golgi apparatus'},
 'RPN2': {'location': 'Endoplasmic reticulum'},
 'RAP1GDS1': {'location': 'Mitochondria'},
 'SERP1': {'location': 'Microtubules'},
 'C2CD2L': {'location': 'Endoplasmic reticulum'},
 'POMK': {'location': 'Endoplasmic reticulum'},
 'TMEM214': {'location': 'Golgi apparatus'},
 'NCLN': {'location': 'Nucleoplasm'},
 'ESYT1': {'location': 'Endoplasmic reticulum'},
 'RAC1': {'location': 'Actin filaments'},
 'TREX1': {'location': 'Cytosol'},
 'DNAJC3': {'location': 'Cytosol'},
 'RPL24': {'location': 'Endoplasmic reticulum'},
 'DDRGK1': {'location': 'Endoplasmic reticulum'},
 'PDGFRA': {'location': 'Plasma membrane'},
 'COPG1': {'location': 'Endoplasmic reticulum'},
 'TECR': {'location': 'Endoplasmic reticulum'},
 'SDC2': {'location': 'Plasma membrane'},
 'POGLUT1': {'location': 'Endoplasmic reticulum'},
 'VCP': {'location': 'Nucleoplasm'},
 'VHL': {'location': 'Nucleoplasm'},
 'RPS13': {'location': 'Actin filaments'},
 'CANX': {'location': 'Endoplasmic reticulum'},
 'HMGB1': {'location': 'Nucleoplasm'},
 'VAPB': {'location': 'Endoplasmic reticulum'},
 'PDGFB': {'location': 'Endoplasmic reticulum'},
 'USE1': {'location': 'Endoplasmic reticulum'},
 'RPS5': {'location': 'Nucleoplasm'},
 'RPS15': {'location': 'Actin filaments'},
 'NCEH1': {'location': 'Endoplasmic reticulum'},
 'ERN1': {'location': 'Endoplasmic reticulum'},
 'DLG1': {'location': 'Plasma membrane'},
 'MTOR': {'location': 'Plasma membrane'},
 'SEC61A1': {'location': 'Endoplasmic reticulum'},
 'SORL1': {'location': 'Golgi apparatus'},
 'RPL10A': {'location': 'Nucleoli'},
 'RPL35': {'location': 'Cytosol'},
 'JAGN1': {'location': 'Endoplasmic reticulum'},
 'UBA52': {'location': 'Mitochondria'},
 'COLGALT2': {'location': 'Nucleoplasm'},
 'STT3B': {'location': 'Endoplasmic reticulum'},
 'LRRTM1': {'location': 'Plasma membrane'},
 'OSBPL6': {'location': 'Cytosol'},
 'OSBPL8': {'location': 'Cytosol'},
 'GRN': {'location': 'Golgi apparatus'},
 'RPL34': {'location': 'Cytosol'},
 'LRRK2': {'location': 'Cytosol'},
 'METTL9': {'location': 'Nucleoplasm'},
 'P4HB': {'location': 'Cytosol'},
 'RPS7': {'location': 'Actin filaments'},
 'ZFYVE27': {'location': 'Nucleoplasm'},
 'RPL17': {'location': 'Endoplasmic reticulum'},
 'BECN1': {'location': 'Nucleoplasm'},
 'COL14A1': {'location': 'Endoplasmic reticulum'},
 'RPS23': {'location': 'Cytosol'},
 'RPS3A': {'location': 'Endoplasmic reticulum'},
 'LRRC25': {'location': 'Microtubules'},
 'DNAJC1': {'location': 'Endoplasmic reticulum'},
 'NOMO1': {'location': 'Cytosol'},
 'RPL21': {'location': 'Cytosol'},
 'SYNE2': {'location': 'Plasma membrane'},
 'UNC93B1': {'location': 'Golgi apparatus'},
 'MGST3': {'location': 'Endoplasmic reticulum'},
 'ERP44': {'location': 'Endoplasmic reticulum'},
 'UBQLN1': {'location': 'Nucleoplasm'},
 'HSP90B1': {'location': 'Actin filaments'},
 'RPL14': {'location': 'Cytosol'},
 'LARP1': {'location': 'Nucleoplasm'},
 'UBC': {'location': 'Cytosol'},
 'ATP2A3': {'location': 'Endoplasmic reticulum'},
 'COPB1': {'location': 'Endoplasmic reticulum'},
 'EMC6': {'location': 'Nucleoplasm'},
 'UBB': {'location': 'Cytosol'},
 'EMC4': {'location': 'Endoplasmic reticulum'},
 'TSPAN15': {'location': 'Plasma membrane'},
 'RPS26': {'location': 'Nucleoplasm'},
 'RPS27': {'location': 'Nucleoplasm'},
 'HRAS': {'location': 'Endoplasmic reticulum'},
 'STX18': {'location': 'Plasma membrane'},
 'EMC8': {'location': 'Endoplasmic reticulum'},
 'CYB5R3': {'location': 'Cytosol'},
 'RAB1A': {'location': 'Golgi apparatus'},
 'EEF1D': {'location': 'Nucleoplasm'},
 'EMD': {'location': 'Endoplasmic reticulum'},
 'GDPD1': {'location': 'Endoplasmic reticulum'},
 'TRAF2': {'location': 'Nucleoplasm'},
 'SLC39A9': {'location': 'Endoplasmic reticulum'},
 'TGFA': {'location': 'Plasma membrane'},
 'RPL36AL': {'location': 'Plasma membrane'},
 'COPE': {'location': 'Cytosol'},
 'TMEM120A': {'location': 'Plasma membrane'},
 'PGRMC2': {'location': 'Endoplasmic reticulum'},
 'TMEM30A': {'location': 'Endoplasmic reticulum'},
 'PPIB': {'location': 'Endoplasmic reticulum'},
 'CYP4F2': {'location': 'Plasma membrane'},
 'REEP2': {'location': 'Microtubules'},
 'PUM3': {'location': 'Nucleoplasm'},
 'RPL23A': {'location': 'Cytosol'},
 'HYOU1': {'location': 'Plasma membrane'},
 'FAF2': {'location': 'Endoplasmic reticulum'},
 'ATG9A': {'location': 'Endoplasmic reticulum'},
 'P4HA1': {'location': 'Endoplasmic reticulum'},
 'CAV1': {'location': 'Actin filaments'},
 'TMED2': {'location': 'Golgi apparatus'},
 'RPS16': {'location': 'Cytosol'},
 'CALR3': {'location': 'Endoplasmic reticulum'},
 'ASGR2': {'location': 'Plasma membrane'},
 'ARCN1': {'location': 'Golgi apparatus'},
 'CREB3': {'location': 'Endoplasmic reticulum'},
 'RPL13': {'location': 'Cytosol'},
 'COL8A1': {'location': 'Endoplasmic reticulum'},
 'TMX2': {'location': 'Nucleoplasm'},
 'GPX8': {'location': 'Plasma membrane'},
 'FAF1': {'location': 'Nucleoplasm'},
 'VMA12': {'location': 'unknown'},
 'BCAP31': {'location': 'Cytosol'},
 'INSIG1': {'location': 'Endoplasmic reticulum'},
 'RPS14': {'location': 'Endoplasmic reticulum'},
 'PDIA3': {'location': 'Actin filaments'},
 'AGPAT3': {'location': 'Golgi apparatus'},
 'REEP5': {'location': 'Endoplasmic reticulum'},
 'SERPINA1': {'location': 'Endoplasmic reticulum'},
 'TMED10': {'location': 'Golgi apparatus'},
 'RPL30': {'location': 'Actin filaments'},
 'UBE2J1': {'location': 'Endoplasmic reticulum'},
 'DNAJB9': {'location': 'Cytosol'},
 'TEX264': {'location': 'Cytosol'},
 'SLC30A1': {'location': 'Plasma membrane'},
 'GOSR2': {'location': 'Golgi apparatus'},
 'STT3A': {'location': 'Endoplasmic reticulum'},
 'BSCL2': {'location': 'Endoplasmic reticulum'},
 'PLPP6': {'location': 'Nuclear membrane'},
 'RINT1': {'location': 'Cytosol'},
 'SEC11C': {'location': 'Nuclear membrane'},
 'GPR89A': {'location': 'Golgi apparatus'},
 'VAPA': {'location': 'Plasma membrane'},
 'KDSR': {'location': 'Endoplasmic reticulum'},
 'GRIN2A': {'location': 'Plasma membrane'},
 'SEC23A': {'location': 'Cytosol'},
 'ATP6AP2': {'location': 'Plasma membrane'},
 'SRP72': {'location': 'Cytosol'},
 'CAMLG': {'location': 'Endoplasmic reticulum'},
 'AGR2': {'location': 'Endoplasmic reticulum'},
 'RPL26L1': {'location': 'Cytosol'},
 'RAB1B': {'location': 'Golgi apparatus'},
 'APLP2': {'location': 'Golgi apparatus'},
 'PLOD3': {'location': 'Endoplasmic reticulum'},
 'TF': {'location': 'Plasma membrane'},
 'INS': {'location': 'Endoplasmic reticulum'},
 'HMOX2': {'location': 'Cytosol'},
 'GDI1': {'location': 'Cytosol'},
 'RETREG3': {'location': 'Nucleoplasm'},
 'PLD3': {'location': 'Endoplasmic reticulum'},
 'ERLIN2': {'location': 'Plasma membrane'},
 'MAGT1': {'location': 'Plasma membrane'},
 'ARLN': {'location': 'unknown'},
 'RPLP0': {'location': 'Actin filaments'},
 'CDIPT': {'location': 'Plasma membrane'},
 'RHOA': {'location': 'Plasma membrane'},
 'PSEN1': {'location': 'Mitochondria'},
 'ZNRF4': {'location': 'Endoplasmic reticulum'},
 'RPS11': {'location': 'Nucleoplasm'},
 'WNT7A': {'location': 'Golgi apparatus'},
 'MARCHF5': {'location': 'Endoplasmic reticulum'},
 'CLEC2D': {'location': 'Plasma membrane'},
 'SGPL1': {'location': 'Endoplasmic reticulum'},
 'GJA1': {'location': 'Mitochondria'},
 'GPC3': {'location': 'Plasma membrane'},
 'YIF1A': {'location': 'Endoplasmic reticulum'},
 'HSPA5': {'location': 'Mitochondria'},
 'SULF2': {'location': 'Endoplasmic reticulum'},
 'GJB1': {'location': 'Endoplasmic reticulum'},
 'SCD': {'location': 'Endoplasmic reticulum'},
 'HLA-E': {'location': 'Golgi apparatus'},
 'APOB': {'location': 'Endoplasmic reticulum'},
 'PGRMC1': {'location': 'Nucleoli'},
 'ELOVL5': {'location': 'Endoplasmic reticulum'},
 'LRRC59': {'location': 'Endoplasmic reticulum'},
 'WFS1': {'location': 'Endoplasmic reticulum'},
 'APH1A': {'location': 'Plasma membrane'},
 'POR': {'location': 'Cytosol'},
 'CYB5B': {'location': 'Endoplasmic reticulum'},
 'AHCYL1': {'location': 'Cytosol'},
 'EMC3': {'location': 'Endoplasmic reticulum'},
 'TSPAN5': {'location': 'Nucleoplasm'},
 'FKBP7': {'location': 'Endoplasmic reticulum'},
 'ARSL': {'location': 'Endoplasmic reticulum'},
 'CLGN': {'location': 'Endoplasmic reticulum'},
 'BCL2': {'location': 'Endoplasmic reticulum'},
 'GET3': {'location': 'Endoplasmic reticulum'},
 'DHRS7': {'location': 'Mitochondria'},
 'TAB1': {'location': 'Cytosol'},
 'RPLP1': {'location': 'Cytosol'},
 'RPS25': {'location': 'Nucleoplasm'},
 'RPL32': {'location': 'Cytosol'},
 'HPN': {'location': 'Plasma membrane'},
 'YBX1': {'location': 'Nucleoplasm'},
 'CALU': {'location': 'Endoplasmic reticulum'},
 'RICTOR': {'location': 'Mitochondria'},
 'CHRNB4': {'location': 'Plasma membrane'},
 'RPL10': {'location': 'Cytosol'},
 'CYBC1': {'location': 'Endoplasmic reticulum'},
 'GORASP2': {'location': 'Endoplasmic reticulum'},
 'NRAS': {'location': 'Cytosol'},
 'ORMDL3': {'location': 'Plasma membrane'},
 'HLA-C': {'location': 'Endoplasmic reticulum'},
 'KPNB1': {'location': 'Nuclear membrane'},
 'FA2H': {'location': 'Endoplasmic reticulum'},
 'COPA': {'location': 'Golgi apparatus'},
 'SEC16A': {'location': 'Golgi apparatus'},
 'EMC1': {'location': 'Endoplasmic reticulum'},
 'STX17': {'location': 'Endoplasmic reticulum'},
 'PDIA4': {'location': 'Endoplasmic reticulum'},
 'ASPH': {'location': 'Plasma membrane'},
 'PINK1': {'location': 'Nucleoplasm'},
 'ORMDL2': {'location': 'Endoplasmic reticulum'},
 'CSGALNACT2': {'location': 'Golgi apparatus'},
 'NOTCH2': {'location': 'Golgi apparatus'},
 'RPS24': {'location': 'Nucleoplasm'},
 'VPS13C': {'location': 'Cytosol'},
 'INSIG2': {'location': 'Endoplasmic reticulum'},
 'PLAUR': {'location': 'Plasma membrane'},
 'DAD1': {'location': 'Endoplasmic reticulum'},
 'EMC2': {'location': 'Endoplasmic reticulum'},
 'ITGB1': {'location': 'Plasma membrane'},
 'OS9': {'location': 'Endoplasmic reticulum'},
 'HLA-DPA1': {'location': 'Golgi apparatus'},
 'MAP3K7': {'location': 'Nucleoplasm'},
 'TOR1A': {'location': 'Nuclear membrane'},
 'RPL8': {'location': 'Nucleoplasm'},
 'DNAJB11': {'location': 'Endoplasmic reticulum'},
 'IFNGR2': {'location': 'Golgi apparatus'},
 'KTN1': {'location': 'Endoplasmic reticulum'},
 'REEP4': {'location': 'Endoplasmic reticulum'},
 'PTPN2': {'location': 'Nucleoplasm'},
 'SEC61B': {'location': 'Endoplasmic reticulum'},
 'CISD2': {'location': 'Endoplasmic reticulum'},
 'DNAJB2': {'location': 'Cytosol'},
 'LGALS1': {'location': 'Plasma membrane'},
 'TMX1': {'location': 'Nucleoli'},
 'SPPL2B': {'location': 'Plasma membrane'},
 'ADPGK': {'location': 'Centrosome'},
 'SYVN1': {'location': 'Nucleoplasm'},
 'RPL38': {'location': 'Plasma membrane'},
 'NINJ2': {'location': 'Plasma membrane'},
 'EMC7': {'location': 'Endoplasmic reticulum'},
 'IGFBP5': {'location': 'Endoplasmic reticulum'},
 'CCDC88A': {'location': 'Golgi apparatus'},
 'COG7': {'location': 'Golgi apparatus'},
 'COG1': {'location': 'Golgi apparatus'},
 'RAB39B': {'location': 'Golgi apparatus'},
 'RAB9A': {'location': 'Cytosol'},
 'MALL': {'location': 'Golgi apparatus'},
 'CD1B': {'location': 'Golgi apparatus'},
 'ZFPL1': {'location': 'Golgi apparatus'},
 'TTR': {'location': 'Golgi apparatus'},
 'TMEM25': {'location': 'Golgi apparatus'},
 'ARRB1': {'location': 'Golgi apparatus'},
 'YES1': {'location': 'Plasma membrane'},
 'TCTN2': {'location': 'Primary cilium'},
 'ATP7A': {'location': 'Plasma membrane'},
 'VPS51': {'location': 'Golgi apparatus'},
 'B4GAT1': {'location': 'Golgi apparatus'},
 'BLZF1': {'location': 'Golgi apparatus'},
 'COPZ1': {'location': 'Golgi apparatus'},
 'ARFIP2': {'location': 'Golgi apparatus'},
 'LDLR': {'location': 'Golgi apparatus'},
 'RAB11A': {'location': 'Actin filaments'},
 'BORCS6': {'location': 'Golgi apparatus'},
 'COG4': {'location': 'Golgi apparatus'},
 'AP1S2': {'location': 'Golgi apparatus'},
 'TMEM74': {'location': 'Cytosol'},
 'GGA1': {'location': 'Golgi apparatus'},
 'RET': {'location': 'Golgi apparatus'},
 'USP33': {'location': 'Golgi apparatus'},
 'GNAI3': {'location': 'Golgi apparatus'},
 'HCST': {'location': 'Golgi apparatus'},
 'GRK2': {'location': 'Golgi apparatus'},
 'STRN3': {'location': 'Golgi apparatus'},
 'GOLPH3L': {'location': 'Golgi apparatus'},
 'GOLIM4': {'location': 'Golgi apparatus'},
 'TNFRSF1A': {'location': 'Plasma membrane'},
 'PCDH10': {'location': 'Golgi apparatus'},
 'VPS52': {'location': 'Golgi apparatus'},
 'GALNT10': {'location': 'Golgi apparatus'},
 'RUSF1': {'location': 'Golgi apparatus'},
 'VAC14': {'location': 'Golgi apparatus'},
 'GGA3': {'location': 'Golgi apparatus'},
 'FUT8': {'location': 'Golgi apparatus'},
 'ACBD3': {'location': 'Golgi apparatus'},
 'ECPAS': {'location': 'Golgi apparatus'},
 'AP1G1': {'location': 'Golgi apparatus'},
 'CD44': {'location': 'Plasma membrane'},
 'OPTN': {'location': 'Golgi apparatus'},
 'PDE4DIP': {'location': 'Golgi apparatus'},
 'CDH1': {'location': 'Golgi apparatus'},
 'ARFGAP1': {'location': 'Plasma membrane'},
 'COG3': {'location': 'Golgi apparatus'},
 'WWOX': {'location': 'Golgi apparatus'},
 'LAMTOR1': {'location': 'Golgi apparatus'},
 'AP1B1': {'location': 'Golgi apparatus'},
 'MUC1': {'location': 'Golgi apparatus'},
 'PLSCR1': {'location': 'Golgi apparatus'},
 'EGFR': {'location': 'Golgi apparatus'},
 'CLTA': {'location': 'Plasma membrane'},
 'GOLPH3': {'location': 'Mitochondria'},
 'GOLGA5': {'location': 'Golgi apparatus'},
 'YIPF6': {'location': 'Golgi apparatus'},
 'C5AR1': {'location': 'Plasma membrane'},
 'MAPKAP1': {'location': 'Cytosol'},
 'AP1M2': {'location': 'Golgi apparatus'},
 'PTCH1': {'location': 'Plasma membrane'},
 'MANSC1': {'location': 'Golgi apparatus'},
 'CBL': {'location': 'Cytosol'},

In [66]:
# get unique compartments
unique_compartments = df_n_comp['location'].unique().tolist()
# add unknown
unique_compartments.append('unknown')
print(unique_compartments)

# make color map for compartments based on "viridis"colormap
import matplotlib.pyplot as plt
cmap = plt.get_cmap('viridis', len(unique_compartments))
compartment_color_map = {}
for i, comp in enumerate(unique_compartments):
    color = cmap(i)  # RGBA tuple
    # Convert to 0-255 range for r, g, b, a
    compartment_color_map[comp] = [int(color[0]*255), int(color[1]*255), int(color[2]*255), 200]
print(compartment_color_map)

['Cytosol', 'Primary cilium', 'Plasma membrane', 'Endoplasmic reticulum', 'Nuclear membrane', 'Centrosome', 'Golgi apparatus', 'Nucleoplasm', 'Nucleoli', 'Mitochondria', 'Intermediate filaments', 'Actin filaments', 'Microtubules', 'unknown']
{'Cytosol': [68, 1, 84, 200], 'Primary cilium': [72, 28, 110, 200], 'Plasma membrane': [69, 53, 128, 200], 'Endoplasmic reticulum': [61, 76, 137, 200], 'Nuclear membrane': [51, 96, 141, 200], 'Centrosome': [43, 116, 142, 200], 'Golgi apparatus': [35, 135, 141, 200], 'Nucleoplasm': [30, 153, 138, 200], 'Nucleoli': [37, 171, 129, 200], 'Mitochondria': [64, 189, 114, 200], 'Intermediate filaments': [103, 204, 92, 200], 'Actin filaments': [151, 216, 62, 200], 'Microtubules': [205, 224, 29, 200], 'unknown': [253, 231, 36, 200]}

In [73]:
# add node attributes to graph as annotation
for n in G.nodes():
    if n in node_attributes:
        G.nodes[n]['annotation'] = dict(location=node_attributes[n]['location'])
        G.nodes[n]['nodecolor'] = compartment_color_map[G.nodes[n]['annotation']['location']]

In [74]:
# print Graph node attributes
for n in G.nodes(data=True):
    print(n)

('STIM1', {'pos': [-3287.009265041689, -5510.379405545829, -5171.142239086409], 'nodecolor': [69, 53, 128, 200], 'annotation': {'location': 'Plasma membrane'}})
('AGPAT4', {'pos': [-291.21538147795275, 4978.437695495098, -492.1721103398928], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('P32969', {'pos': [1064.3113626289314, 1142.134944984536, 59.42814693103409], 'nodecolor': [253, 231, 36, 200], 'annotation': {'location': 'unknown'}})
('RPL27A', {'pos': [2141.6079254793417, 3283.753560757641, -1058.2937816410606], 'nodecolor': [30, 153, 138, 200], 'annotation': {'location': 'Nucleoplasm'}})
('NCK1', {'annotation': {'location': 'Plasma membrane'}, 'nodecolor': [69, 53, 128, 200], 'pos': [0.0, 0.0, 0.0]})
('APOA2', {'pos': [-3112.915356923353, 1815.125125908884, 3464.670931179256], 'nodecolor': [68, 1, 84, 200], 'annotation': {'location': 'Cytosol'}})
('BSG', {'pos': [-5425.812800384063, 2262.549986508764, -91.22588680456954], 'nodecolor': [35, 135, 141, 200], 'annotation': {'location': 'Golgi apparatus'}})
('EMC10', {'pos': [-3786.287055326392, 1570.1400883028105, 2883.196828070472], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('PTPN1', {'pos': [-3090.467431463872, 7125.08433370967, -2667.4318106087394], 'nodecolor': [69, 53, 128, 200], 'annotation': {'location': 'Plasma membrane'}})
('TMED9', {'pos': [-4833.917252077993, 323.0185982259746, 1248.938958338907], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('GPR37', {'pos': [-6337.628596425501, -4621.937830468985, -4131.297596071653], 'nodecolor': [69, 53, 128, 200], 'annotation': {'location': 'Plasma membrane'}})
('DNAJA1', {'pos': [98.8729754462178, 7230.915450053474, -2028.160531627809], 'nodecolor': [68, 1, 84, 200], 'annotation': {'location': 'Cytosol'}})
('ORMDL1', {'pos': [3009.439798461941, 3819.627868061313, 1217.792076503525], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('TMPRSS3', {'pos': [-2710.7970128274437, 3047.000308061228, 2895.1276446050565], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('PTPN5', {'pos': [4587.846904009746, 13.301688593668132, 1999.5529673710523], 'nodecolor': [30, 153, 138, 200], 'annotation': {'location': 'Nucleoplasm'}})
('TPTE', {'pos': [1849.2889518317368, -2861.768441945259, 3667.607319304378], 'nodecolor': [68, 1, 84, 200], 'annotation': {'location': 'Cytosol'}})
('BET1', {'annotation': {'location': 'Golgi apparatus'}, 'nodecolor': [35, 135, 141, 200], 'pos': [0.0, 0.0, 0.0]})
('DDOST', {'pos': [-4058.6697062964654, -5429.00791451469, 4883.285605672527], 'nodecolor': [69, 53, 128, 200], 'annotation': {'location': 'Plasma membrane'}})
('RNF19B', {'pos': [-227.1525573278606, 2959.693729477623, -2726.606748280236], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('ATXN3', {'annotation': {'location': 'Nucleoplasm'}, 'nodecolor': [30, 153, 138, 200], 'pos': [0.0, 0.0, 0.0]})
('ERLIN1', {'pos': [2641.778937628338, -2072.1608776928256, 3355.424814583196], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('RNF185', {'pos': [2012.4635777416213, 389.92091758620927, 3953.885549178941], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('COL5A1', {'pos': [-2504.6399822547687, 69.06768865060015, -4342.602215782626], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('FGFR3', {'pos': [-2538.68958585321, -5350.363362123918, 5597.250880106135], 'nodecolor': [69, 53, 128, 200], 'annotation': {'location': 'Plasma membrane'}})
('SOAT1', {'pos': [-3186.7183050444314, 361.513397053253, 3832.95761985542], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('CDK1', {'pos': [-5701.687724912264, 2252.461781438811, 95.39452161279512], 'nodecolor': [64, 189, 114, 200], 'annotation': {'location': 'Mitochondria'}})
('IER3IP1', {'pos': [928.4939564532094, 4912.135973369839, -258.88740955651343], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('RPS2', {'pos': [792.6141117102973, 1208.5656159665, 23.105017234539304], 'nodecolor': [30, 153, 138, 200], 'annotation': {'location': 'Nucleoplasm'}})
('HMOX1', {'annotation': {'location': 'Endoplasmic reticulum'}, 'nodecolor': [61, 76, 137, 200], 'pos': [0.0, 0.0, 0.0]})
('FAM20C', {'pos': [-809.9598458882225, 459.78302620533134, 6140.108482441524], 'nodecolor': [35, 135, 141, 200], 'annotation': {'location': 'Golgi apparatus'}})
('ESYT2', {'pos': [-3110.028514427251, -2491.853053929696, -7183.984439318995], 'nodecolor': [69, 53, 128, 200], 'annotation': {'location': 'Plasma membrane'}})
('PDZD8', {'pos': [-8352.585987082719, 1961.0125742849543, -3928.300710842161], 'nodecolor': [37, 171, 129, 200], 'annotation': {'location': 'Nucleoli'}})
('CDC42', {'pos': [4092.848858546867, 6394.474493933839, -3487.9399159621776], 'nodecolor': [43, 116, 142, 200], 'annotation': {'location': 'Centrosome'}})
('COMT', {'pos': [-3861.08719662708, -4484.345845253332, -5851.523041110553], 'nodecolor': [69, 53, 128, 200], 'annotation': {'location': 'Plasma membrane'}})
('RPL10L', {'pos': [2431.9407191761084, -1008.057903117076, -4267.523180524447], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('UFL1', {'pos': [-1192.5353775677102, -3996.018403577378, 2745.4561428756697], 'nodecolor': [30, 153, 138, 200], 'annotation': {'location': 'Nucleoplasm'}})
('CFTR', {'pos': [2140.326538193363, -5940.578884763384, 5052.346906809056], 'nodecolor': [69, 53, 128, 200], 'annotation': {'location': 'Plasma membrane'}})
('YWHAE', {'pos': [-5728.307488858231, 2230.1124507602744, -58.27078819113631], 'nodecolor': [64, 189, 114, 200], 'annotation': {'location': 'Mitochondria'}})
('PTDSS1', {'pos': [177.28170758284446, 1571.0139435740275, 4746.243048758825], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('MAP3K5', {'pos': [3989.544749245479, -384.8694663379151, -3008.024193952166], 'nodecolor': [68, 1, 84, 200], 'annotation': {'location': 'Cytosol'}})
('PRKCA', {'pos': [117.94915793722816, 41.03632779282412, 8911.591198154401], 'nodecolor': [30, 153, 138, 200], 'annotation': {'location': 'Nucleoplasm'}})
('RNF5', {'pos': [3080.255298683843, 2119.644693567011, 2995.6920104579226], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('PLN', {'pos': [2849.9870678353063, 4095.403172883982, 448.2056888518312], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('CGRRF1', {'pos': [-186.51980649065487, 4820.898227523649, 1340.4906779431662], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('CALR', {'pos': [-2930.4336420904297, 2359.0842681198515, 7274.506663962796], 'nodecolor': [151, 216, 62, 200], 'annotation': {'location': 'Actin filaments'}})
('TMBIM6', {'pos': [2650.9218935249783, 3039.5679452865625, 22.9962251440273], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('RPS6', {'pos': [730.2191518772013, 1015.2988145487818, 67.13740209014944], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('ACE2', {'pos': [771.2896010782391, -4044.154980178139, 6861.880561186917], 'nodecolor': [69, 53, 128, 200], 'annotation': {'location': 'Plasma membrane'}})
('NOTCH1', {'annotation': {'location': 'Cytosol'}, 'nodecolor': [68, 1, 84, 200], 'pos': [0.0, 0.0, 0.0]})
('RPS29', {'pos': [1195.3550437007486, -5176.192245917583, 7044.750801303676], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('CLU', {'pos': [-5596.293713513295, 2311.272102331902, 37.17119511806318], 'nodecolor': [68, 1, 84, 200], 'annotation': {'location': 'Cytosol'}})
('EEF1G', {'pos': [723.2081523722895, 108.80920861433546, 6342.393914762194], 'nodecolor': [68, 1, 84, 200], 'annotation': {'location': 'Cytosol'}})
('TAP1', {'pos': [-3475.4081733164376, 1350.4930214120814, -1539.504986544934], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('SSR1', {'pos': [-708.9812659438544, -3263.481022896464, 3700.83383420173], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('RPS27A', {'annotation': {'location': 'Mitochondria'}, 'nodecolor': [64, 189, 114, 200], 'pos': [0.0, 0.0, 0.0]})
('LMAN1', {'pos': [-2607.9759948292963, -1944.03014779818, 2374.951842014337], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('UGT8', {'pos': [-4541.515381793512, 2059.259054946928, 436.3794999886129], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('SCAP', {'pos': [-574.8063655926721, 217.9153308483301, 6269.16664682623], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('CKAP4', {'pos': [-5570.24340432061, 2286.925071558116, -283.1736981517604], 'nodecolor': [69, 53, 128, 200], 'annotation': {'location': 'Plasma membrane'}})
('ARL6IP5', {'pos': [-1257.208525318768, 1281.1124732711507, 4668.5961518209], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('MAPK3', {'pos': [-5692.137868004929, 2241.186285624376, 227.385326753024], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('PSEN2', {'pos': [-728.8439060864523, -752.0259810434947, -3913.2618283185566], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('WLS', {'pos': [-8727.219435997504, -3432.177032871851, -1870.2643625214355], 'nodecolor': [69, 53, 128, 200], 'annotation': {'location': 'Plasma membrane'}})
('UFD1', {'pos': [4845.876023396297, -1204.9688657387114, -384.65428879209054], 'nodecolor': [30, 153, 138, 200], 'annotation': {'location': 'Nucleoplasm'}})
('ADAMTSL4', {'pos': [5280.171438936583, -6318.574450869784, 2485.3838461760924], 'nodecolor': [69, 53, 128, 200], 'annotation': {'location': 'Plasma membrane'}})
('LNPK', {'pos': [188.10112185601807, 2253.2516363640902, 3334.233083430729], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('AMFR', {'pos': [3374.5476890233003, -719.5053960108932, 2092.2566387213305], 'nodecolor': [35, 135, 141, 200], 'annotation': {'location': 'Golgi apparatus'}})
('STUB1', {'pos': [-1502.5475735906052, 1361.539592487019, 2909.9320252761977], 'nodecolor': [30, 153, 138, 200], 'annotation': {'location': 'Nucleoplasm'}})
('EBP', {'pos': [-2466.626461175256, 2567.451842369302, 1801.113694559882], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('SAR1A', {'annotation': {'location': 'Endoplasmic reticulum'}, 'nodecolor': [61, 76, 137, 200], 'pos': [0.0, 0.0, 0.0]})
('PRKN', {'annotation': {'location': 'Nucleoplasm'}, 'nodecolor': [30, 153, 138, 200], 'pos': [0.0, 0.0, 0.0]})
('FAM234B', {'pos': [-3989.1529699997977, 2945.356954438937, 716.3895023626476], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('SEL1L', {'pos': [2770.014075765768, -2930.1595693939366, 2955.431172707717], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('UBIAD1', {'pos': [-1666.220740835795, 3420.233726827804, 1344.0150925219773], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('SACM1L', {'pos': [-580.7249022839551, -319.99106392274183, 6001.430619086785], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('RPS21', {'annotation': {'location': 'Nucleoplasm'}, 'nodecolor': [30, 153, 138, 200], 'pos': [0.0, 0.0, 0.0]})
('PDIA6', {'pos': [2196.4406140886745, -4396.863186279869, 897.7674984177773], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('ARSK', {'pos': [-4764.546714211661, -466.4917607444702, -1459.4448273087812], 'nodecolor': [30, 153, 138, 200], 'annotation': {'location': 'Nucleoplasm'}})
('ERLEC1', {'pos': [2914.8703950670315, -1124.0990223752146, 2549.682445445556], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('TMEM97', {'pos': [-1834.3671386623296, 2917.9542325146463, 2114.172718071084], 'nodecolor': [69, 53, 128, 200], 'annotation': {'location': 'Plasma membrane'}})
('RPN1', {'annotation': {'location': 'Cytosol'}, 'nodecolor': [68, 1, 84, 200], 'pos': [0.0, 0.0, 0.0]})
('RTN3', {'pos': [-4874.017698199748, -7489.11956195006, 2123.989169622708], 'nodecolor': [35, 135, 141, 200], 'annotation': {'location': 'Golgi apparatus'}})
('HLA-B', {'annotation': {'location': 'Endoplasmic reticulum'}, 'nodecolor': [61, 76, 137, 200], 'pos': [0.0, 0.0, 0.0]})
('COPB2', {'pos': [-376.3563284273948, -581.0325495669448, 6028.006102143096], 'nodecolor': [68, 1, 84, 200], 'annotation': {'location': 'Cytosol'}})
('AUP1', {'pos': [2199.358738922336, -2985.729857703972, 3153.8803535252364], 'nodecolor': [30, 153, 138, 200], 'annotation': {'location': 'Nucleoplasm'}})
('KRAS', {'pos': [-5714.670806865899, 2236.3671732731154, -126.13228643400842], 'nodecolor': [68, 1, 84, 200], 'annotation': {'location': 'Cytosol'}})
('FN1', {'pos': [-1797.451117092122, 7500.0534005191375, 2348.1193848791727], 'nodecolor': [69, 53, 128, 200], 'annotation': {'location': 'Plasma membrane'}})
('RPS8', {'pos': [1483.1240947624733, 3042.7043851131216, -2171.17912964288], 'nodecolor': [69, 53, 128, 200], 'annotation': {'location': 'Plasma membrane'}})
('CNPY3', {'pos': [-1830.331903422925, 3770.840325945282, -6895.219431757556], 'nodecolor': [69, 53, 128, 200], 'annotation': {'location': 'Plasma membrane'}})
('RPL26', {'pos': [681.8387195102225, 1190.3887921748903, -36.317998157964325], 'nodecolor': [68, 1, 84, 200], 'annotation': {'location': 'Cytosol'}})
('FDFT1', {'pos': [1139.7529062823014, 3182.492219237306, 3691.883350465583], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('RPL28', {'pos': [2839.5727641087365, -2838.782896339764, -2996.0628988499766], 'nodecolor': [68, 1, 84, 200], 'annotation': {'location': 'Cytosol'}})
('ELOVL4', {'pos': [1067.983770590783, 4398.765624311602, 1895.392838817009], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('RPS3', {'pos': [860.0969875282307, 1069.772903597525, 31.177060518659545], 'nodecolor': [68, 1, 84, 200], 'annotation': {'location': 'Cytosol'}})
('TMEM86B', {'pos': [1129.5255981286807, 4132.626791711059, 2577.858800524947], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('PLOD1', {'pos': [-1786.0356904538685, 341.96506122476904, -4670.451450978419], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('CDK5RAP3', {'pos': [3447.7396225360253, 5517.324191353383, 4302.673056617462], 'nodecolor': [205, 224, 29, 200], 'annotation': {'location': 'Microtubules'}})
('JPH3', {'pos': [-2508.830566545584, -822.0949329577334, -1478.6323179211568], 'nodecolor': [30, 153, 138, 200], 'annotation': {'location': 'Nucleoplasm'}})
('UBA1', {'pos': [-5791.275834700947, 2143.22579069115, 51.26644081487933], 'nodecolor': [30, 153, 138, 200], 'annotation': {'location': 'Nucleoplasm'}})
('EIF2AK3', {'pos': [-4383.581328463202, -1833.6278723323048, 1532.3798733995163], 'nodecolor': [68, 1, 84, 200], 'annotation': {'location': 'Cytosol'}})
('COL4A5', {'pos': [-8823.010952255087, -5228.059160421437, -591.6008566772606], 'nodecolor': [69, 53, 128, 200], 'annotation': {'location': 'Plasma membrane'}})
('SEC22B', {'pos': [-152.24545520340698, 52.724432527936536, 5602.81884869552], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('ATP2A2', {'pos': [-307.6096262918959, -7534.759115524798, 2671.703668961151], 'nodecolor': [69, 53, 128, 200], 'annotation': {'location': 'Plasma membrane'}})
('ARL6IP1', {'pos': [-629.6372820246921, 4719.783731782344, 1556.1325017999147], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('REEP6', {'pos': [-1395.5834104304308, 3886.65694993477, 2837.6071369488754], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('MIA3', {'pos': [-3015.896197005144, -1815.095622232774, 3534.6801444783523], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('RPS20', {'pos': [1103.7568388717891, 3724.9380737468, -1191.1995204747782], 'nodecolor': [30, 153, 138, 200], 'annotation': {'location': 'Nucleoplasm'}})
('BNIP1', {'pos': [-730.423100270717, 4815.166834541129, 1152.3502247888782], 'nodecolor': [64, 189, 114, 200], 'annotation': {'location': 'Mitochondria'}})
('NPLOC4', {'pos': [4547.3005814227, -1812.5179382262872, 1045.027184783479], 'nodecolor': [68, 1, 84, 200], 'annotation': {'location': 'Cytosol'}})
('GIMAP1', {'pos': [-80.07839447901401, 4980.131868031147, 554.5160091398907], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('COPG2', {'annotation': {'location': 'Cytosol'}, 'nodecolor': [68, 1, 84, 200], 'pos': [0.0, 0.0, 0.0]})
('SEC62', {'pos': [8476.127309964031, 2119.383215882499, -2689.0501626977043], 'nodecolor': [103, 204, 92, 200], 'annotation': {'location': 'Intermediate filaments'}})
('CCDC47', {'pos': [-866.2898740177823, -496.05809657476186, 3900.299720705736], 'nodecolor': [68, 1, 84, 200], 'annotation': {'location': 'Cytosol'}})
('DERL2', {'pos': [2649.147468227475, -774.664753004668, 4170.147525842311], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('RPL5', {'pos': [790.1779409985961, 1155.2626330960293, 147.52378952903314], 'nodecolor': [30, 153, 138, 200], 'annotation': {'location': 'Nucleoplasm'}})
('RTN4', {'pos': [-4329.072460954119, -7072.536112094545, -1369.7544307799712], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('RPL37A', {'pos': [212.0447077364377, 368.14623633744463, 8787.101726897168], 'nodecolor': [68, 1, 84, 200], 'annotation': {'location': 'Cytosol'}})
('SRPRB', {'pos': [-7148.257290194915, -5318.310636167907, -1744.946985077711], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('STX5', {'pos': [187.8885948623591, 188.98067425015844, 5644.610491497416], 'nodecolor': [35, 135, 141, 200], 'annotation': {'location': 'Golgi apparatus'}})
('RPL7', {'pos': [906.0013919873012, 1070.9885941845005, 126.3735268925239], 'nodecolor': [68, 1, 84, 200], 'annotation': {'location': 'Cytosol'}})
('ATP2A1', {'pos': [548.2156249826643, 3876.6714851264505, -917.4831799437908], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('HADHB', {'pos': [-5331.938658687185, 1953.3231057275243, -135.46089075597095], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('APP', {'pos': [-5615.811953903924, 2143.124450895825, -84.55153170419116], 'nodecolor': [68, 1, 84, 200], 'annotation': {'location': 'Cytosol'}})
('STING1', {'pos': [-4460.238064072107, -4794.461695571223, 6448.591434681253], 'nodecolor': [68, 1, 84, 200], 'annotation': {'location': 'Cytosol'}})
('TMED7', {'pos': [787.0468343927943, -397.4573281434518, 5786.1737513260105], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('EDEM1', {'pos': [980.0112009903792, -3116.636503083677, 3492.1330131821496], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})
('SEC63', {'pos': [-1217.4056402932547, -1483.8480622811946, 3583.262482828779], 'nodecolor': [61, 76, 137, 200], 'annotation': {'location': 'Endoplasmic reticulum'}})

In [75]:
# for nodes without position assign position 0,0,0  

nodes_without_pos = [n for n in G.nodes() if 'pos' not in G.nodes[n]]
print(f"Nodes without position: len(nodes_without_pos) = {len(nodes_without_pos)}")
for n in G.nodes():
    if 'pos' not in G.nodes[n]:
        G.nodes[n]['pos'] = [0.0, 0.0, 0.0]

Nodes without position: len(nodes_without_pos) = 0

In [83]:
# link colors 
for u, v in G.edges():
    G.edges[u, v]['linkcolor'] = [60,60,60, 100]

✅ Connected to /main

# make VR project with Graph

In [84]:
print("Number of nodes: ", len(G.nodes()))
print("Number of Links: ", len(G.edges()))

# ===============================================
# GRAPH NAME AND DESCRIPTION - a string each
# ===============================================

G.graph['projectname'] = "0_SpatialPPI_Elias"
G.graph['info'] = "A spatial PPI graph for testing purposes. Number of nodes: "+str(len(G.nodes()))+", Links: "+ str(len(G.edges()))+"."

Number of nodes:  18346
Number of Links:  308377

In [85]:
# set node names (optional)
#for n in G.nodes():
#    G.nodes[n]['name'] =

In [86]:
nx2j.create_project(G)

Successfully created the directory static/projects/0_SpatialPPI_Elias
PROGRESS: loaded graph JSON...
PROGRESS: stored graph data...
PROGRESS: stored layouts...
PROGRESS: stored node info...
PROGRESS: made node position textures...
PROGRESS: made textures for node colors...
PROGRESS: made textures for links...
PROGRESS: made textures for linkcolors...
PROGRESS: writing json files for project and nodes...
Project created successfully.

✅ Connected to /main
✅ Connected to /main
✅ Connected to /main
✅ Connected to /main
✅ Connected to /main

# REALTIME

In [80]:
import networkx as nx 
from dataXplorer import JupyterClient
from dataXplorer import AnalysisToolkit, SessionManager, TextureGenerator, ProjectFileManager, VisualizerSyncer

In [81]:
# run backend (server) using buildandrun powershell script
client = JupyterClient()

#client.disconnect()

✅ Connected to /main

✅ Connected to /main
✅ Connected to /main

In [79]:
# see if new project is in projectlist
import GlobalData as GD

allprojects_updated = []
for i, proj in enumerate(GD.listProjects()):
    allprojects_updated.append((i,proj))
allprojects_updated

[(0, '0_SpatialPPI_Elias'),
 (1, 'AE_Memes_2022'),
 (2, 'ARS23_memes'),
 (3, 'ByzNet-1400-people-only'),
 (4, 'ByzNet_PxL'),
 (5, 'CDK5'),
 (6, 'CircLadderGraph-xsmall'),
 (7, 'diffusion'),
 (8, 'JSON_autocore'),
 (9, 'JSON_barbellgraph'),
 (10, 'JSON_Zachary'),
 (11, 'Microplastics_HumanHealth'),
 (12, 'Pesticides_HumanHealth'),
 (13, 'PG_NEW'),
 (14, 'Powergrid_Europe'),
 (15, 'PPI_brain_infarction'),
 (16, 'PPI_joel_daniel_aryan'),
 (17, 'PPI_joel_daniel_aryan_C'),
 (18, 'PPI_joel_daniel_aryan_test_1'),
 (19, 'PPI_networkcartoGRAPHs'),
 (20, 'Realtime-project'),
 (21, 'Sphere_Torus'),
 (22, 'Teapot'),
 (23, 'Template'),
 (24, 'test'),
 (25, 'TheMandelbulb_edges'),
 (26, 'XX')]

In [82]:
# select a project to work with
sel_id = 0
sel_name = allprojects_updated[sel_id][1]

# load the project data
session = SessionManager(sel_id, sel_name, client)
session.load_graph_from_project()
session.reload_project()

# initialize 
file_mgr = ProjectFileManager(session)
tex_gen = TextureGenerator(session)
syncer = VisualizerSyncer(session)

Session Graph loaded from project folder.
Project name:  0_SpatialPPI_Elias
Data: Nodes: 18346 Links: 308377

# THE FOLLOWING SECTION IS JUST FOR BACKGROUND INFO - no need to run
This is how the graph is storing all information given nx.Graph(s).

In [ ]:
'''

{
----------------------------------------
THIS IS THE GENERAL GRAPH INFO SECTION
----------------------------------------
  "directed": false,
  "multigraph": false,
  "projectname": "Testgraph",
  "info": "A toy graph for testing purposes. Number of nodes: 10, Links: 43.",
  "graphlayouts": [
      "layout1-spring",
      "layout2-spring",
      "layout3-spring",
      "layout4-clusters"
  ],
  "annotationTypes": true,
  "nodes": [
   ----------------------------------------
   contains all nodes of the project
   ----------------------------------------
      {
          "id": 0,
          "name": nodename-x,
          "annotation": 
                {
                    "annot1": [
                        "lambda",
                        "alpha",
                        "zeta",
                        "theta"
                    ],
                    "annot2": [
                        "delta",
                        "nu"
                    ],
                    "annot3": [
                        "mu",
                        "gamma"
                    ]
          }
      },....
  ],
  "links": [
   ----------------------------------------
   contains all links of the project
   ----------------------------------------
      {
          "id": 0,
          "source": 0,
          "target": 1
      },
      {
          "id": 1,
          "source": 0,
          "target": 2
      },...
       ],
  "layouts": [
   ----------------------------------------
   contains all layouts of the project
   only contains nodes and links as well as colors specific to the layout
   ----------------------------------------
       {  "layoutname" : "name of first layout",
          "nodes": [
              {
                  "nodecolor": [
                      255,
                      35,
                      0,
                      120
                  ],
                  "pos": [
                      -0.5618057865250979,
                      0.1467411221839164,
                      0.49656801102094605
                  ],
                  "id": 0
               },...
        	],
          "links": [
              {
                  "linkcolor": [
                      0,
                      255,
                      0,
                      100
                  ],
                  "source": 0,
                  "target": 1
              },...
         	],
   	  }, {
          "layoutname" : "name of second layout",
          "nodes": [
              {
                  "nodecolor": "#0000ffaa",
                  "pos": [
                      -0.35948900932978317,
                      0.6255258442839948,
                      -0.04209289102217994
                  ],
                  "cluster": "cluster group 1",
                  "id": 0
               },... 
],
          "links": [
              {
                  "linkcolor": "#0000ff",
                  "source": 0,
                  "target": 1
              },
],
  	   }, { . . .  
 	},
}

'''

## CREATE A JSON FILE WITH THE ABOVE STRUCTURE to then create a project

In [28]:
import networkx as nx
import json 
import os

# these are the two functions one needs to create a JSON file to upload and then create the project in the backend 
import nx2json as nx2j 
import uploaderGraph as uG

In [14]:
# ----------------------------------------
# CREATE Json file
# ----------------------------------------
merged_graphs = nx2j.make_json(Graphs)
path = "temp_files/"

# save the merged graph in a json file
with open(path+Graphs[0].graph['projectname']+'.json', 'w') as fp:
    json.dump(merged_graphs, fp, indent=4)

In [ ]:
# ----------------------------------------
# READ Json file
# ----------------------------------------
filename = 'myfile.json'
currentwd = '.../DataDiVR_Webapp/temp_files/' # modify file location here
path = os.path.join(currentwd, filename)

# open the json file
with open(path, 'r') as f:
     G_merged = json.load(f)

In [ ]:
## ----------------------------------------
# CREATE A PROJECT for the VR Platform 
# ----------------------------------------
#the actual "upload step" to create a project with the required VR platform files 

uG.upload_filesJSON(G_merged)